#cloud-config
package_update: true
packages:
  - curl
  - unzip
  - apt-transport-https
  - lsb-release
  - gnupg

runcmd:
  - curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

write_files:
  - path: /home/azureuser/upload.sh
    permissions: '0755'
    owner: azureuser:azureuser
    content: |
      #!/bin/bash
      STORAGE_ACCOUNT="teststorage187"
      CONTAINER_NAME="uploads"

      FILE_PATH="$1"
      BLOB_NAME=$(basename "$FILE_PATH")

      echo "Prihlasovani pomoci RBAC"
      az login --identity >/dev/null

      echo "Nahravam soubor"
      az storage blob upload \
        --account-name "$STORAGE_ACCOUNT" \
        --container-name "$CONTAINER_NAME" \
        --name "$BLOB_NAME" \
        --file "$FILE_PATH" \
        --auth-mode login

      echo "Nahravani dokonceno"